# Generated by Django 3.0 on 2020-10-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='type',
            new_name='typ',
        ),
    ]
