# Generated by Django 3.0 on 2020-10-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201010_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/None/Noimg.jpg', upload_to='Images/'),
        ),
    ]
